import fs from 'fs';
import path from 'path';
import { reviewCode } from '../lib/agent.js';
import { renderReport } from '../lib/renderer.js';
import chalk from 'chalk';

const SUPPORTED = {
  '.js': 'JavaScript', '.jsx': 'JavaScript', '.mjs': 'JavaScript',
  '.ts': 'TypeScript', '.tsx': 'TypeScript',
  '.py': 'Python',
  '.java': 'Java',
  '.go': 'Go',
  '.rb': 'Ruby',
  '.php': 'PHP',
  '.rs': 'Rust',
  '.c': 'C', '.cpp': 'C++', '.h': 'C/C++',
  '.cs': 'C#',
  '.swift': 'Swift',
  '.kt': 'Kotlin',
  '.sh': 'Bash',
  '.sql': 'SQL',
};

export async function reviewCommand(file, options) {
  // Validate file exists
  const filePath = path.resolve(file);
  if (!fs.existsSync(filePath)) {
    console.error(chalk.red(`\n  ✗ File not found: ${filePath}\n`));
    process.exit(1);
  }

  const ext = path.extname(filePath).toLowerCase();
  const detectedLang = options.lang || SUPPORTED[ext] || 'auto';
  const filename = path.basename(filePath);
  const code = fs.readFileSync(filePath, 'utf8');

  if (code.trim().length === 0) {
    console.error(chalk.red('\n  ✗ File is empty.\n'));
    process.exit(1);
  }

  console.log(chalk.gray(`\n  Reviewing: ${chalk.cyan(filename)}  [${detectedLang}]`));
  console.log(chalk.gray(`  Size: ${code.split('\n').length} lines, ${code.length} chars\n`));

  // Spinner
  const frames = ['⠋','⠙','⠹','⠸','⠼','⠴','⠦','⠧','⠇','⠏'];
  let i = 0;
  const steps = [
    'Detecting language & structure...',
    'Scanning for bugs & edge cases...',
    'Running security analysis...',
    'Evaluating code quality...',
    'Generating fixed version...',
  ];
  let stepIdx = 0;
  const spinner = setInterval(() => {
    process.stdout.write(`\r  ${chalk.cyan(frames[i++ % frames.length])}  ${chalk.gray(steps[stepIdx % steps.length])}`);
    if (i % 15 === 0) stepIdx++;
  }, 80);

  try {
    const result = await reviewCode({ code, language: detectedLang, filename });
    clearInterval(spinner);
    process.stdout.write('\r' + ' '.repeat(60) + '\r');

    renderReport(result, {
      showFix: options.fix,
      minSeverity: options.severity,
      jsonMode: options.json,
    });

    // Save to file if requested
    if (options.output) {
      const outPath = path.resolve(options.output);
      const ext2 = path.extname(outPath);

      if (ext2 === '.json') {
        fs.writeFileSync(outPath, JSON.stringify(result, null, 2));
      } else {
        fs.writeFileSync(outPath, buildMarkdownReport(result, filename));
      }
      console.log(chalk.greenBright(`  ✓ Report saved to: ${outPath}\n`));
    }

    // Exit code based on critical issues
    const criticals = result.metrics?.criticalCount || 0;
    if (criticals > 0) {
      console.log(chalk.redBright(`  ⚠  ${criticals} critical issue(s) found — exiting with code 1\n`));
      process.exit(1);
    }

  } catch (err) {
    clearInterval(spinner);
    process.stdout.write('\r' + ' '.repeat(60) + '\r');
    console.error(chalk.red(`\n  ✗ Error: ${err.message}\n`));
    process.exit(1);
  }
}

function buildMarkdownReport(result, filename) {
  const lines = [
    `# CodeSentinel Report — ${filename}`,
    `**Score:** ${result.score}/10 (${result.scoreLabel})`,
    `**Language:** ${result.language}`,
    '',
    '## Summary',
    result.summary,
    '',
    '## Issues',
  ];

  (result.issues || []).forEach(issue => {
    lines.push(`\n### [${issue.severity.toUpperCase()}] ${issue.title}`);
    lines.push(`- **Category:** ${issue.category}`);
    lines.push(`- **Location:** ${issue.line}`);
    lines.push(`- **Description:** ${issue.description}`);
    lines.push(`- **Fix:** ${issue.fix}`);
  });

  if (result.fixedCode) {
    lines.push('\n## Fixed Code');
    lines.push('```');
    lines.push(result.fixedCode);
    lines.push('```');
  }

  lines.push(`\n---\n*Generated by CodeSentinel on ${new Date().toISOString()}*`);
  return lines.join('\n');
}
