import fs from 'fs';
import path from 'path';
import { reviewCode } from '../lib/agent.js';
import { renderReport, renderScanSummary } from '../lib/renderer.js';
import chalk from 'chalk';

export async function scanCommand(directory, options) {
  const dirPath = path.resolve(directory);

  if (!fs.existsSync(dirPath)) {
    console.error(chalk.red(`\n  ✗ Directory not found: ${dirPath}\n`));
    process.exit(1);
  }

  const exts = options.ext.split(',').map(e => '.' + e.trim().replace(/^\./, ''));
  const ignorePatterns = options.ignore.split(',').map(p => p.trim());

  // Collect all matching files
  const files = collectFiles(dirPath, exts, ignorePatterns);

  if (files.length === 0) {
    console.log(chalk.yellow(`\n  No files found with extensions: ${exts.join(', ')}\n`));
    process.exit(0);
  }

  console.log(chalk.bold.cyan(`\n  🔍 Scanning ${files.length} file(s) in ${dirPath}\n`));

  const results = [];

  for (let idx = 0; idx < files.length; idx++) {
    const filePath = files[idx];
    const relPath = path.relative(dirPath, filePath);
    const progress = `[${idx + 1}/${files.length}]`;

    process.stdout.write(`  ${chalk.gray(progress)} ${chalk.cyan(relPath)} — analyzing...`);

    try {
      const code = fs.readFileSync(filePath, 'utf8');
      if (code.trim().length === 0) {
        process.stdout.write(`  ${chalk.gray('(empty, skipped)')}\n`);
        continue;
      }

      const result = await reviewCode({ code, filename: relPath });
      const score = result.score || 0;
      const scoreStr = score >= 8 ? chalk.greenBright(`${score}/10`) : score >= 5 ? chalk.yellow(`${score}/10`) : chalk.redBright(`${score}/10`);
      const crit = result.metrics?.criticalCount || 0;
      const critStr = crit > 0 ? chalk.redBright(` ⚠ ${crit} critical`) : '';
      process.stdout.write(`\r  ${chalk.gray(progress)} ${chalk.cyan(relPath)} — ${scoreStr}${critStr}\n`);

      results.push({ file: relPath, result });
    } catch (err) {
      process.stdout.write(`\r  ${chalk.gray(progress)} ${chalk.cyan(relPath)} — ${chalk.red('ERROR: ' + err.message)}\n`);
      results.push({ file: relPath, error: err.message });
    }
  }

  // Print summary table
  renderScanSummary(results);

  // Save report if requested
  if (options.output) {
    const outPath = path.resolve(options.output);
    const report = buildFullReport(results, dirPath);
    fs.writeFileSync(outPath, report);
    console.log(chalk.greenBright(`  ✓ Full report saved to: ${outPath}\n`));
  }

  // Exit 1 if any criticals
  const hasCriticals = results.some(r => (r.result?.metrics?.criticalCount || 0) > 0);
  if (hasCriticals) process.exit(1);
}

function collectFiles(dir, exts, ignorePatterns) {
  const results = [];

  function walk(current) {
    let entries;
    try { entries = fs.readdirSync(current, { withFileTypes: true }); }
    catch { return; }

    for (const entry of entries) {
      const fullPath = path.join(current, entry.name);
      const shouldIgnore = ignorePatterns.some(p =>
        entry.name === p || fullPath.includes(path.sep + p + path.sep)
      );
      if (shouldIgnore) continue;

      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).toLowerCase();
        if (exts.includes(ext)) results.push(fullPath);
      }
    }
  }

  walk(dir);
  return results;
}

function buildFullReport(results, dirPath) {
  const lines = [
    `# CodeSentinel Scan Report`,
    `**Directory:** ${dirPath}`,
    `**Date:** ${new Date().toISOString()}`,
    `**Files Scanned:** ${results.length}`,
    '',
    '## Per-File Results',
  ];

  results.forEach(({ file, result, error }) => {
    lines.push(`\n### ${file}`);
    if (error) {
      lines.push(`> ❌ Error: ${error}`);
      return;
    }
    lines.push(`**Score:** ${result.score}/10 | **Critical:** ${result.metrics?.criticalCount || 0} | **Warnings:** ${result.metrics?.warningCount || 0}`);
    lines.push(`\n${result.summary}`);
    (result.issues || []).forEach(issue => {
      lines.push(`\n- **[${issue.severity.toUpperCase()}]** ${issue.title} (${issue.line})`);
      lines.push(`  ${issue.description}`);
    });
  });

  lines.push('\n---\n*Generated by CodeSentinel*');
  return lines.join('\n');
}
